version: '3.0'
services:
  app:
    container_name: nuxt
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports: 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data
