version: '3.0'
services:
  redis:
    image: redis:6.0.4-alpine
    container_name: spotify-player-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data
