version: '3.0'

services:
  client:
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
      target: dev-stage
    container_name: ravyd_client
    tty: true
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - ./packages/client/.env.development
    environment:
      - CLIENT_PORT
    volumes:
      - .:/app
      # Exclude node_modules & server directories
      - node_modules:/app/node_modules
      - server:/app/packages/server

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      target: dev-stage
    container_name: ravyd_server
    tty: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - ./packages/server/.env.development
    environment:
      - SERVER_PORT
    depends_on:
      - redis
    volumes:
      - .:/app
      # Exclude node_modules & client directories
      - node_modules:/app/node_modules
      - client:/app/packages/client

  redis:
    container_name: redis
    build: ./packages/server/redis
    env_file:
      - ./packages/server/.env.development
    environment:
      - REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis:
  node_modules:
  client:
  server:
