version: '3.0'
services:
  app:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: nuxt
    tty: true
    ports:
      - 3000:3000
    env_file: 
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data
