version: '3.0'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: dev-stage
    container_name: nuxt
    tty: true
    ports:
      - 3000:3000
    env_file:
      - ./client/.env.development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: dev-stage
    container_name: server
    tty: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - ./server/.env.development
    environment:
      - SERVER_PORT
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    build: ./server/redis
    env_file:
      - ./server/.env.development
    environment:
      - REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - redis-session:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis-session:
