version: '3.0'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: dev-stage
    container_name: nuxt
    tty: true
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - ./client/.env.development
    environment:
      - CLIENT_PORT
    volumes:
      - .:/app
      # Exclude node_modules & server directories
      - node_modules:/app/node_modules
      - server:/app/server

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: dev-stage
    container_name: server
    tty: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - ./server/.env.development
    environment:
      - SERVER_PORT
    depends_on:
      - redis
    volumes:
      - .:/app
      # Exclude node_modules & client directories
      - node_modules:/app/node_modules
      - client:/app/client

  redis:
    image: redis:6.0.4-alpine
    container_name: redis
    build: ./server/redis
    env_file:
      - ./server/.env.development
    environment:
      - REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  redis:
  node_modules:
  client:
  server:
