# This file must be run at project root.

steps:
  # Build
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--file"
      - "./packages/server/Dockerfile"
      - "--target"
      - "prod-stage"
      - "."

  # Push to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--port"
      - "${_PORT}"
      - "--timeout"
      - "20"
      - "--cpu"
      - "1"
      - "--memory"
      - "256Mi"
      - "--max-instances"
      - "30"
      - "--allow-unauthenticated"
      - "--no-traffic"

  # Update Cloud Run traffic
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - "run"
      - "services"
      - "update-traffic"
      - "${_SERVICE_NAME}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--to-latest"

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"

timeout: 1200s

# substitutions:
#   COMMIT_SHA:
#   _REGION:
#   _REPOSITORY_NAME:
#   _SERVICE_NAME:
#   _PORT:
