name: lint & type checking & vtc & test

on:
  push:
    branches: [ develop, master, main ]
  pull_request:
    branches: [ develop, master, main ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        yarn --frozen-lockfile --production=false
    - name: Run ESLint & styleLint
      run: yarn run lint && yarn stylelint
    - name: Type Checking
      run: yarn tsc
    - name: Run vtc
      run: yarn vtc
    - name: Run test
      run: yarn test
